
#端口号
server:
  port: 8880
#  context-path: /aaa
#视图解析
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
 #编码过滤
  http:
    encoding:
      charset: utf-8
      force: true
# #数据源
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/cmfz
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#注册mapper
mybatis:
  mapper-locations: com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity